# Generated by Django 5.0.6 on 2024-06-23 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_clientes_cliente'),
        ('productos', '0002_rename_productos_producto'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detalles',
            new_name='Detalle',
        ),
        migrations.RenameModel(
            old_name='Ventas',
            new_name='Venta',
        ),
    ]
