# Generated by Django 5.0.6 on 2024-06-23 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_alter_producto_id_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.marca'),
        ),
    ]
