# Generated by Django 5.0.6 on 2024-06-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_clientes_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['cedula']},
        ),
    ]
